[calendars]

  [[khal_calendar]]
  path = ~/.calendars/khal/*
  type = discover

  [locale]
  timeformat = %H:%M
  dateformat = %Y-%m-%d
  longdateformat = %Y-%m-%d
  datetimeformat = %Y-%m-%d %H:%M
  longdatetimeformat = %Y-%m-%d %H:%M

  [default]
  default_calendar = personal
  highlight_event_days = True
  timedelta = 7d

   # vim: set ft=toml